version: "3.3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=catanatron
      - POSTGRES_PASSWORD=victorypoint
      - POSTGRES_DB=catanatron_db
    ports:
      - 5432:5432
  server:
    build: .
    environment:
      - DATABASE_URL=postgresql://catanatron:victorypoint@db:5432/catanatron_db
    ports:
      - "5000:5000"
    stdin_open: true
    volumes:
      - .:/app
  # react-ui:
  #   build: ./ui
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   volumes:
  #     - /app/node_modules
  #     - ./ui:/app
