[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

# [dev-packages]
# pytest-watch = "*"
# coverage = "*"
# black = "*"
# pytest = "*"
# coveralls = "*"
# snakeviz = "*"
# pytest-benchmark = "*"
# ipython = "*"
# # Dependencies for Catanatron Research (Experimental)
# click = "*"
# termplotlib = "*"
# tensorflow = "*"
# pandas = "*"
# scikit-learn = "==0.24.0"
# jupyterlab = "*"
# matplotlib = "*"

[packages]
# Depedencies for Catanatron Server
flask = "*"
flask-cors = "*"
psycopg2-binary = "*"
catanatron = {editable = true, path = "."}
gunicorn = "*"

[requires]
python_version = "3.8"

[pipenv]
allow_prereleases = true
