version: 2
workflows:
  experiment-workflow:
    steps:
      -
        name: "my-experiment"
        command: experiment.run_single_node
        params:
          command: nvidia-smi
          container: bcollazo/paperspace-rl
          experimentEnv:
            EPOCHS_EVAL: 2
            EVAL_SECS: 10
            MAX_STEPS: 100
            TRAIN_EPOCHS: 3
          machineType: p2.xlarge
          modelPath: /artifacts
          modelType: Tensorflow
          name: gradientci-sample
          clusterId: clbdo1h0q
        checks: #[optional]
          tensorflow:loss:
            target: "0.0..0.5"
            aggregate: "mean"
          defaults: #[optional]
            precision: 3
      triggers:
        branches:
          only: master
